var graph = {
"nodes":[
{"name":"al-Ṣāliḥ Najm al-Dīn Ayyūb","date":"r. 637-647/1240-1249","Gender":"M","group":"Ayyubids","rank":"sultan"},
{"name":"Shajar al-Durr","date":"r. 648/1250","Gender":"F","group":"Early Mamlūks","rank":"sultan"},
{"name":"al-Muʿizz Aybak","date":"r. 648-655/1250-1257","Gender":"M","group":"Early Mamlūks","rank":"sultan"},
{"name":"al-Manṣūr ʿAlī","date":"r. 655-657/1257-1259","Gender":"M","group":"Early Mamlūks","rank":"sultan"},
{"name":"al-Muẓaffar Quṭuz","date":"r. 657-658/1259-1260","Gender":"M","group":"Early Mamlūks","rank":"sultan"},
{"name":"aẓ-Ẓāhir Baybars","date":"r. 658-676/1260-1277","Gender":"M","group":"Baybars","rank":"sultan"},
{"name":"as-Saʿīd Berka Khān","date":"r. 676-678/1277-1279","Gender":"M","group":"Baybars","set":"Sons of Baybars","rank":"sultan"},
{"name":"al-ʿĀdil Salamish","date":"r. 678/1279","Gender":"M","group":"Baybars","set":"Sons of Baybars","rank":"sultan"},
{"name":"al-Manṣūr Qalāwūn","date":"r. 678-689/1279-1290","Gender":"M","group":"Qalāwūnids","rank":"sultan"},
{"name":"al-Ashraf Khalīl","date":"r. 689-693/1290-1293","Gender":"M","group":"Qalāwūnids","set":"Sons","rank":"sultan"},
{"name":"an-Nāṣir Muḥammad","date":"r. 693–694/1293–1294; 698–708/1299–1309; 709–741/1310-1341","Gender":"M","group":"Qalāwūnids","rank":"sultan"},
{"name":"al-ʿĀdil Kitbughā","date":"r. 694-696/1294-1296","Gender":"M","group":"Amirs","set":"Manṣūrī Amirs","rank":"sultan"},
{"name":"al-Manṣūr Lājīn","date":"r. 696-698/1296-1298","Gender":"M","group":"Amirs","set":"Manṣūrī Amirs","rank":"sultan"},
{"name":"al-Muẓaffar Baybars al-Jāshankīr","date":"r. 708-709/1308-1310","Gender":"M","group":"Amirs","set":"Manṣūrī Amirs","rank":"sultan"},   
{"name":"al-Manṣūr Abū Bakr","date":"r. 741–742/1341","Gender":"M","group":"Qalāwūnids","set":"Grandsons","rank":"sultan"},
{"name":"al-Ashraf Kujuk","date":"r. 742/1341–1342","Gender":"M","group":"Qalāwūnids","set":"Grandsons","rank":"sultan"},
{"name":"an-Nāṣir Aḥmad","date":"r. 742–743/1342","Gender":"M","group":"Qalāwūnids","set":"Grandsons","rank":"sultan"},
{"name":"aṣ-Ṣāliḥ Ismāʿīl","date":"r. 743–746/1342–1345","Gender":"M","group":"Qalāwūnids","set":"Grandsons","rank":"sultan"},
{"name":"al-Kāmil Shaʿbān","date":"r. 746–747/1345–1346","Gender":"M","group":"Qalāwūnids","set":"Grandsons","rank":"sultan"},
{"name":"al-Muẓaffar Ḥājjī","date":"r. 747–748/1346–1347","Gender":"M","group":"Qalāwūnids","set":"Grandsons","rank":"sultan"},
{"name":"an-Nāṣir Ḥasan","date":"r. 748–752/1347–1351, 755–762/1354–1361","Gender":"M","group":"Qalāwūnids","set":"Grandsons","rank":"sultan"},
{"name":"aṣ-Ṣāliḥ Ṣāliḥ","date":"r. 752–755/1351–1354","Gender":"M","group":"Qalāwūnids","set":"Grandsons","rank":"sultan"},
{"name":"al-Manṣūr Muḥammad","date":"r. 762–764/1361–1363","Gender":"M","group":"Qalāwūnids","set":"Great Grandsons","rank":"sultan"},
{"name":"al-Ashraf Shaʿbān","date":"r. 764–778/1363–1377","Gender":"M","group":"Qalāwūnids","set":"Great Grandsons","rank":"sultan"},
{"name":"al-Manṣūr ʿAlī","date":"r. 778–783/1377–1381","Gender":"M","group":"Qalāwūnids","set":"Great Great Grandsons","rank":"sultan"},
{"name":"aṣ-Ṣāliḥ Ḥājjī","date":"r. 783–784/1381–1382, 791–792/1389–1390","Gender":"M","group":"Qalāwūnids","set":"Great Great Grandsons","rank":"sultan"},
{"name":"aẓ-Ẓāhir Barqūq","date":"r. 784-792/1382-1389 , 792-801/1390-1399","Gender":"M","group":"Amirs","rank":"sultan"},
{"name":"Relative of al-Ṣāliḥ Najm al-Dīn Ayyūb","date":"d. unknown","Gender":"F","group":"Ayyubids"},
{"name":"Bint aẓ-Ẓāhir Baybars","date":"d. unknown","Gender":"F","group":"Baybars","set":"Baybars' son"},
{"name":"Relative of al-Manṣūr Lājīn","date":"d. unknown","Gender":"F","group":"Awlād al-Nās"},
{"name":"Shaktāy","date":"","Gender":"M","group":"Non-Mamlūks"},
{"name":"Ashlun bint Shaktāy","date":"d. unknown","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Zawjat Qalāwūn","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Umm aṣ-Ṣāliḥ","date":"d. 683/1284","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"aṣ-Ṣāliḥ ʿAlī","date":"d. 1288","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Mankabay b. Nughāy","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Mūsá","date":"d. 718/1318-9","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Ardūkin b. Nughāy","date":"d. 724/1324","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Khātūn","date":"d. before 689/1290","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Nughāy","date":"","Gender":"M","group":"Non-Mamlūks"},
{"name":"Salār","date":"d. 710/1310","Gender":"M","group":"Amirs","set":"Manṣūrī amir"},
{"name":"Bint Salār","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Ṭughāy","date":"d. 749/1348-9","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Ṭulunbāy bint Ṭughāy","date":"d. 741/1340","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Manklībughā al-Silāḥdār","date":"d. 731/1330","Gender":"M","group":"Nāṣirī Amirs"},
{"name":"ʿUmar ibn Arghūn al-Nāṣirī al-Nāʾib","date":"d. Unknown","Gender":"M","group":"Awlād al-Nās"},
{"name":"Arghūn al-Nāṣirī al-Nāʾib","date":"","Gender":"M","group":"Amirs","set":"Nāṣirī amīr"},
{"name":"Abū Bakr ibn Arghūn al-Nāṣirī al-Nāʾib","date":"","Gender":"M","group":"Awlād al-Nās"},
{"name":"Ṣūṣūn","date":"d. 734/1334","Gender":"M","group":"Amirs"},
{"name":"Qawṣūn","date":"d. 742/1342","Gender":"M","group":"Amirs","set":"Nāṣirī amīr"},
{"name":"Ukht Qawṣūn","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Khalīl ibn Qawṣūn","date":"d. 778/1376","Gender":"M","group":"Awlād al-Nās"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 1","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 2","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 3","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 4","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 5","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 6","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 7","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Zawjat al-Malik al-Nāsir Muḥammad 1","date":"d. after 747/1346","Gender":"F","group":"Qalāwūnid Royal Wives"},  
{"name":"Zawjat al-Malik al-Nāsir Muḥammad 2","date":"d. Unknown","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Zawjat al-Malik al-Nāsir Muḥammad 3","date":"d. Unknown","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Bayāḍ","date":"d. 731/1330-1","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Narjis","date":"d. after 756/1356","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Kudā","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Ḥusayn","date":"d. 764/1363","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Arghūn al-ʿAlāʾī","date":"","Gender":"M","group":"Amirs","set":"Nāṣirī amīr"},
{"name":"Lājīn al-ʿAlāʾī","date":"","Gender":"M","group":"Amirs"},
{"name":"Shaykhū","date":"","Gender":"M","group":"Amirs","set":"Nāṣirī (Ḥasan) Amirs"},
{"name":"Qumārī","date":"","Gender":"M","group":"Amirs"},
{"name":"Ānūk ibn al-Malik al-Nāṣir Muḥammad","date":"d. 741/1340","Gender":"M","group":"Qalāwūnīd prince"},
{"name":"Bint Baktamur al-Sāqī","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Baktamur al-Sāqī","date":"","Gender":"M","group":"Amirs","set":"Nāṣirī amīr"},
{"name":"Aḥmad ibn Baktamur al-Sāqī","date":"d. 733/1332","Gender":"M","group":"Awlād al-Nās"},
{"name":"Quṭlūmalik bint Tankiz al-Ḥusāmī","date":"d. after 755/1354","Gender":"F","group":"Awlād al-Nās"},
{"name":"Tankiz al-Ḥusāmī","date":"d. 741/1341","Gender":"M","group":"Amirs","set":"Nāṣirī amīr"},
{"name":"Aḥmad ibn Tankiz al-Ḥusāmī","date":"","Gender":"M","group":"Awlād al-Nās"},
{"name":"Muḥammad ibn Tankiz al-Ḥusāmī","date":"","Gender":"M","group":"Awlād al-Nās"},
{"name":"Ṭāẓ","date":"","Gender":"M","group":"Amirs","set":"Nāṣirī (Ḥasan) Amirs"},
{"name":"Bint Ṭāẓ","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Ṭuquzdamur al-Ḥamawī","date":"d. 746/1345","Gender":"M","group":"Amirs"},
{"name":"Bint Ṭuquzdamur al-Ḥamawī 1","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Maliktamur al-Sarjuwānī","date":"","Gender":"M","group":"Amirs"},
{"name":"Ṭāyirbughā","date":"d. 738/1337","Gender":"M","group":"Amirs"},
{"name":"Bint Ṭāyirbughā 1","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Arghūn al-Ismāʿīlī","date":"d. Unknown","Gender":"M","group":"Amirs"},
{"name":"Yūsuf","date":"d. 747/1346","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint Jankalī ibn al-Bābā","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Jankalī ibn al-Bābā","date":"","Gender":"F","group":"Amirs","set":"Manṣūrī Amirs"},
{"name":"Ittifāq","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Zawjat al-Ṣāliḥ Ismāʿīl 1","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Bint al-Ṣāliḥ Ismāʿīl","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 9","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Zahrāʾ","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Kaydā","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"al-Sitt Ḥadaq","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Ṭūlūbiyya bint ʿAbd Allāh al-Nāṣiriyya","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Ibn Yalbughā al-ʿUmarī al-Nāṣirī","date":"","Gender":"M","group":"Awlād al-Nās"},
{"name":"Yalbughā al-ʿUmarī al-Nāṣirī","date":"","Gender":"M","group":"Amirs","set":"Nāṣirī (Ḥasan) Amirs"},
{"name":"Aḥmad","date":"","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Nāṣir Ḥasan 1","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Shaqrāʾ","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Urūs","date":"","Gender":"M","group":"Amirs"},
{"name":"Tatar al-Ḥijāziyyah","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Sayf al-dīn Ṭughāytamur al-ʿUmarī al-Nāṣirī","date":"","Gender":"M","group":"Amirs"},
{"name":"Maliktamur al-Ḥijāzī","date":"","Gender":"M","group":"Amirs"},
{"name":"Tankizbughā","date":"","Gender":"M","group":"Amirs"},
{"name":"Bint Tankizbughā","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Bint al-Malik al-Nāṣir Muḥammad 8","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Tankizbughā al-Māridānī","date":"","Gender":"M","group":"Amirs"},
{"name":"Ardū","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Ibrāhīm","date":"","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint Ṭuquzdamur al-Ḥamawī 2","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Ḥūṭūn Khātūn","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Jankalī ibn al-Bābā","date":"","Gender":"M","group":"Amirs","set":"Manṣūrī Amirs"},
{"name":"Bint Ṭāyirbugha 2","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Baraka","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Uljāy al-Yūsūfī","date":"","Gender":"M","group":"Amirs","set":"Nāṣirī (Ḥasan) amir"},
{"name":"Qāsim al-Bashtakī","date":"","Gender":"M","group":"Amirs"},
{"name":"Ānaṣ","date":"d. 783/1382","Gender":"M","group":"Non-Mamlūks"},
{"name":"Bint Ṭughāytamur al-Niẓāmī","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Ṭughāytamur al-Niẓāmī","date":"","Gender":"M","group":"Amirs"},
{"name":"Khawand bint Manklībughā","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Manklībughā","date":"","Gender":"M","group":"Amirs"},
{"name":"Sāra","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Fāṭima","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Zawjat al-Ashraf Shaʿbān 1","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Bint al-Malik al-Ashraf Shaʿbān 2","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Yalbughā al-Aḥmadī al-Majnūn","date":"","Gender":"M","group":"Amirs"},
{"name":"Hājar","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Khadīja","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Zawjat al-Malik al-Ashraf Shaʿbān 2","date":"","Gender":"F","group":"Qalāwūnid Royal Wives"},
{"name":"Ṣalāḥ al-dīn Muḥammad ibn Muḥammad ibn Tankiz al-Ḥusāmī","date":"","Gender":"M","group":"Awlād al-Nās"},
{"name":"Āqbughā ʿAbd al-Wāḥid al-Nāṣirī","date":"","Gender":"M","group":"Amirs"},
{"name":"Bint Aḥmad","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Aḥmad","date":"d. 783/1381","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint al-Malik al-Ashraf Shaʿbān 1","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Minṭāsh","date":"","Gender":"M","group":"Amirs"},
{"name":"ʿĀʾisha al-Qurdumiyya","date":"","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"Qurdum al-Nāṣirī al-Ḥamawī","date":"","Gender":"M","group":"Amirs"},
{"name":"Bint aẓ-Ẓāhir Baybars","date":"","Gender":"F","group":"Baybars","set":"Sons of Baybars"},
{"name":"Daughter of Byzantine Emperor","date":"","Gender":"F","group":"Non-Mamlūks"},
{"name":"Bint al-ʿĀdil Kitbughā","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Baydarā al-ʿĀdilī","date":"","Gender":"M","group":"Amirs"},
{"name":"Zawjat Ṭuquzdamur al-Ḥamawī","date":"","Gender":"F","group":"Awlād al-Nās"},
{"name":"Baygharā","date":"","Gender":"M","group":"Amirs"},
{"name":"Bahādur al-Damurdāshī","date":"","Gender":"M","group":"Amirs"},
{"name":"Āqsunqur al-Nāṣirī","date":"","Gender":"M","group":"Amirs","set":"Nāṣirī Amirs"},
{"name":"Yaḥya ibn Ṭāyirbughā","date":"","Gender":"M","group":"Awlād al-Nās"},
{"name":"Zakariyyā ibn Ṭāyirbughā","date":"","Gender":"M","group":"Awlād al-Nās"},
{"name":"ʿAlī","date":"d. 783/1381","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Abū Bakr","date":"d. 803/1400","Gender":"M","group":"Qalāwūnid Princes & Princesses"},    
{"name":"Aḥmad","date":"d. before 783/1381","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Ramaḍān","date":"d. before 783/1381","Gender":"M","group":"Qalāwūnid Princes & Princesses"},    
{"name":"Qāsim","date":"d. before 783/1381","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Muḥammad","date":"d. before 783/1381","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Ismāʿīl","date":"d. 797/1395","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"al-Malik al-Manṣūr Ānūk","date":"d. 793/1390-1","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Jānibak","date":"d. 831/1428","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Aḥmad","date":"d. Unknown","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Ibrāhīm","date":"d. Unknown","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Qāsim","date":"d. Unknown","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Ibrāhīm","date":"d. 783/1381","Gender":"M","group":"Qalāwūnid Princes & Princesses"},
{"name":"Bint Tankiz al-Ḥusāmī 2","date":"d. Unknown","Gender":"F","group":"Awlād al-Nās"},
{"name":"ʿĀʾisha","date":"d. Unknown","Gender":"F","group":"Qalāwūnid Princes & Princesses"},
{"name":"ʿIzz al-dīn Ṭuqṭāy","date":"d. Unknown","Gender":"M","group":"Amirs"}    
],
"links": [ 
{"source": 1, "target": 0, "value": 1},
{"source": 2, "target": 1, "value": 2}
]
}  
